language: csharp
solution: MercadoPagoCore.sln

mono: none

dotnet: 5.0.100

script:
  - dotnet restore
  - dotnet build --configuration Release --no-restore
  - dotnet test --no-restore --verbosity normal
